### ISSUE TITLE
Demo applications are missing or not public

### ISSUE THREAD

**Issue by ColinEberhardt** [deislabs/wagi#12]
The documentation points to the following examples:
- env_wagi: Dump the environment that WAGI sets up, including env vars and args.
- hello-wagi-as: AssemblyScript example using environment variables and query params.

Neither of which are publicly available.

**Comment by radu-matei** [comment]
Thanks a lot for reporting this, the two repositories are now public as well.

See https://github.com/deislabs/env_wagi and https://github.com/deislabs/hello-wagi-as.
