### ISSUE TITLE
WebSocket Support

### ISSUE THREAD

**Issue by Ronsor** [deislabs/wagi#124]
As the title suggests, it would be nice if WAGI's implementation of the CGI standard were extended to support WebSockets, even if the handshake would have to be performed by the executed module.

**Comment by radu-matei** [comment]
Hi, @Ronsor, thanks a lot for opening this issue.

Could you please give a bit of context to what you had in mind for WebSockets support?

There are two main directions where the "WebSockets support" discussion could go:

- something like Wagi would be a WebSockets server, and would instantiate a Wasm module to handle each incoming connection
- guest modules in Wagi would be able to create outbound WebSocket client connections to external servers -- this is similar to the outbound HTTP library (https://github.com/deislabs/wasi-experimental-http).

Which of the two are you thinking about?

**Comment by Ronsor** [comment]
I'm referring to adding support for a WebSocket server. Although outbound connections would also be useful, I think being able to handle incoming connections would be more useful for now.

I would submit a pull request adding myself; however, I do not have any experience working with Rust.

**Comment by radu-matei** [comment]
I see.
While this would definitely be useful, I _think_ it falls a bit outside the scope of Wagi, which is intended as an implementation of the CGI specification for WebAssembly modules.

That being said, once `witx-bindgen` (https://github.com/bytecodealliance/witx-bindgen) supports streams and async functions, we could implement this more easily, and I'd be happy to give it a try (as a separate project from Wagi).

**Comment by bacongobbler** [comment]
Yeah, the two are mutually exclusive client/server protocols. The Websocket protocol is described in [rfc6455](https://datatracker.ietf.org/doc/html/rfc6455). CGI 1.1 is described in [rfc3875](https://datatracker.ietf.org/doc/html/rfc3875).

I could definitely see WebSocket support being something very useful for WebAssembly, but it falls out of scope for this project.

Thanks for your interest!
