### ISSUE TITLE
Do we want to add arm64 binaries to the release job?

### ISSUE THREAD

**Issue by vdice** [deislabs/wagi#141]
Wondering if we want to add arm64 binaries to the release job?  I'm personally interested in a linux arm64 binary, but I'd think we could also add darwin and win at the same time if we wanted.

Does anyone have experience using arm64-based GH action agents?  Last I checked, there didn't appear to be any 'stock' arm64 agent flavors available... anyone have experience with https://github.com/marketplace/actions/run-on-architecture (Linux only)?

**Comment by radu-matei** [comment]
I'm wondering if we could perhaps directly cross-compile Rust to ARM64 — https://www.rohanjain.in/cargo-cross
A few months ago I tested on an ARM64 Rasberry Pi, and I recall being able to cross compile to it from my AMD CPU.

Re: Darwin support, I don't see any activity on https://github.com/actions/virtual-environments/issues/2187.
Perhaps @squillace might have some insight?

**Comment by vdice** [comment]
Another reference for cross-compilation, specifically via GH actions, which is what we want here: https://github.com/krustlet/krustlet/blob/a303840c1fd86f2e07f687be47a137be2ecfd326/.github/workflows/build.yml#L55-L68

Thanks for the link @bacongobbler.  cc @adamreese

**Comment by vdice** [comment]
Linux aarch64 has been added.

Check out https://github.com/deislabs/bindle/blob/main/.github/workflows/release.yaml for a pattern on how to add Mac/Darwin aarch64.

**Comment by technosophos** [comment]
Closing, now that we actually just _shipped ARM support_ 🎈
