### ISSUE TITLE
the gnosis network don't have a logo

### ISSUE THREAD

**Issue by travelfroggame** [deislabs/wagi#191]
![image](https://user-images.githubusercontent.com/127594949/229081817-7c3d5e03-c4a3-4904-b6ba-83693d3dce2f.png)

**Comment by radu-matei** [comment]
Hi, @travelfroggame!
I'm not sure I follow how the issue is connected to this repository. Would you mind expanding on this?

Thanks.

**Comment by travelfroggame** [comment]
> Hi, @travelfroggame! I'm not sure I follow how the issue is connected to this repository. Would you mind expanding on this?
> 
> Thanks.

I don't know where to add a LOGO to it

**Comment by radu-matei** [comment]
This repository has nothing to do with Gnosis, so I am not sure how we can help.

**Comment by travelfroggame** [comment]
oh, After my observation, the problem on the rainbowkit side
