### ISSUE TITLE
Allow modules to dynamically register sub-paths and map to functions

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#21]
Say we have a module declared like this:

```toml
[[module]]
route = "/hello"
module = "my.wasm"
```

It would be nice for the module to be able to claim several sub-routes, and have those mapped automatically. For example, the module may want to add a `/hello/foo` path that maps to the function `foo()` and a `/hello/bar` path that maps to `bar()`.

We could create a reserved function name that WAGI can call to register subpaths. For example, we could map the `_routes()` function for this. The expectation is that the function would return a TOML document that described its routes:

```toml
[[route]]
path = "/foo"
entrypoint = "foo"


[[route]]
path = "/bar"
entrypoint = "bar"
```

The module's base path (`/hello`) would then be combined with the `_route()`'s relative paths to form absolute paths (`/hello/foo` and `/hello/bar`). This would prevent a module from usurping another module's namespace. (And would be easier to debug)

The TOML structure makes it possible for us to add new dynamic configuration in the future. But I think the above represents the minimal.

Now, when it comes to generating the lookup tables, WAGI could take a few strategies:

- It could generate the full path lookup table every time that it loaded. This is obviously heavy in cost.
- It could call `_routes()` only when a prefix was matched. So if the client sends `/hello/foo/bar/baz`, WAGI would do a prefix match on its known routes, find that a module matched the prefix, and then invoke the `_routes()` call on the module to find out if `/foo/bar/baz` matched one of the subpaths

Of course, neither of these approaches preclude caching.

**Comment by radu-matei** [comment]
I think this is a great idea!
Do we want to enforce TOML for this though? We could simplify and just have space-separated `<path> <entrypoint>` new lines instead of already serialized data.

Also, could we run the module's `_route` function only once, at the first invocation of the module, instead of every time a prefix matches?

**Comment by technosophos** [comment]
We probably could do a simpler format. The only downside would be that it would prevent us from extending this. But maybe simplicity is the right first step here/

If we called the `_route()` function once on startup, we could do everything in a single pass and cache it. The only downside is that if you re-deployed a module, you'd have to re-start/reload the server.

**Comment by radu-matei** [comment]
That's a good point - that being said, until we actually need to extend the format, maybe we should not force additional dependencies like serializers?
(we'd need to write our own AssemblyScript serializer for this scenario, for example).

I don't think I have a strong preference for when to invoke `_route` - but I think we already need to restart the server if we add a new module anyway, right?

**Comment by technosophos** [comment]
Okay, you have definitely won me over on the plain text format idea. I'm thinking the most obvious format would be:

```
PATH [FUNC_NAME]
```

Where PATH is required, and [FUNC_NAME] is optional, defaulting to `_start`.

My point on the _route thing is that if I am actively developing a module, every time I updated the module with a new path I would have to restart the server. But now that I think about it, that's not really a showstopper. So I think for the first pass we should go with your suggestion of assembling the list of paths on startup
