### ISSUE TITLE
Improve loading speed

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#3]
Right now, WAGI loads the WASM module at request time. Big WASM modules can take seconds to load.

There is probably a way to cache or preload modules to speed this up. wasm3 interprets rather than JIT-ing, and that might be substantially faster in this case (though I don't think wasm3 currently has WASI support).

**Comment by radu-matei** [comment]
There have been a few improvements in the Wasmtime ecosystem over the last few months around startup time:

- the Wasmtime cache, which is now enabled for WAGI in #19 
- [Wizer](https://github.com/bytecodealliance/wizer) - this works great for modules with costly initializing functions.

It might make sense to add a readme section that talks about startup performance and some considerations.

**Comment by technosophos** [comment]
Oh, yeah... we totally should.

**Comment by radu-matei** [comment]
I agree, and even more with the instantiation improvements from Wasmtime.
