### ISSUE TITLE
Credentials for authenticating to private registries

### ISSUE THREAD

**Issue by radu-matei** [deislabs/wagi#41]
The current OCI support added in #39 only allows pulling anonymously from OCI registries.
There should be a way to pass credentials to authenticate to a private registry.

**Comment by technosophos** [comment]
Do we think we want credentials in the `modules.toml`, passed via CLI, or in a separate file altogether? We might be able to use the same format that Docker does.

**Comment by radu-matei** [comment]
On one hand, it would be really convenient to have a single file for everything.
At the same time, I have used a `modules.toml` file to configure sensitive environment variables, and I would very much prefer having a separate credential file for this.

**Comment by nitishm** [comment]
I will pick this up

**Comment by radu-matei** [comment]
@nitishm -- let me know what your thoughts are here.
I haven't really thought about this issue very much lately, so I'm curious how you want to approach it.

**Comment by nitishm** [comment]
@radu-matei i haven't had a chance  to work on this last week. I plan to spend some time this week. I will let you know what I am thinking 🙂

**Comment by nitishm** [comment]
@radu-matei I am considering using a credentials file with password in b64. And (maybe) additional a CLI flag?

**Comment by radu-matei** [comment]
That could definitely work.

One other option would be to reuse the Docker configuration file.
[`wasm-to-oci`](https://github.com/engineerd/wasm-to-oci) expects the Docker CLI to be already authenticated to the desired container registry -- this ensures that both straightforward auth works, but also things like `az act login`, or `gcloud auth`, which directly append the token to the Docker config file.

We could take the same approach here -- this has the advantage of reusing the existing ways to authenticate to container registries, but adds the dependency on that file and format.

I'm ok with either approach, not really sure which option would be better.
What do you think?

Thanks for looking into this!

**Comment by nitishm** [comment]
Leveraging the docker auth sounds much cleaner. I would rather not store credentials in the clear. I will look into how it can be done. If it's too hard (for me as a rust amateur) I will switch to the CLI flag based option & config file

**Comment by nitishm** [comment]
@radu-matei for clarity are we looking to use the docker config file as a credential store for a **new** set of basic auth credentials to authenticate with private registeries or are we looking to re-use the creds from existing authenticated entries in the docker config (which I suppose can be fetched using the docker ["credential helper](https://docs.docker.com/engine/reference/commandline/login/#credentials-store)" methods?

**Comment by nitishm** [comment]
@radu-matei @technosophos I am thinking of leveraging https://github.com/keirlawson/docker_credential crate for this. Any thoughts?
The idea is to,
1. docker login (or any other CLI based login) that adds the auth creds to `.docker/config.json`'s `auth` section.
2. When running wagi, pass in the registry name as an arg and use it to lookup the registry creds using the docker-credential-helper crate.

Let me know if that makes sense and I can get cranking.

**Comment by technosophos** [comment]
Yeah, I think that crate totally makes sense.
