### ISSUE TITLE
Support setting maximum concurrent requests for the HTTP library

### ISSUE THREAD

**Issue by radu-matei** [deislabs/wagi#42]
There is currently no support for setting the maximum number of concurrent requests a guest module can perform.
Since the HTTP library supports it, we should expose it as a field in the module config as well:

https://github.com/deislabs/wasi-experimental-http/blob/6a6226ead5ae2335ccde0a7e9a0b4a128d46249f/crates/wasi-experimental-http-wasmtime/src/lib.rs#L296-L298

**Comment by nitishm** [comment]
I would like to take a stab at this. @radu-matei can you point me to the right vicinity in the code where the change needs to occur?

**Comment by nitishm** [comment]
I found the `HttpCtx::new()` call in `run_wasm()` and `load_routed()` methods in mod.rs. I have opened #106 to encapsulate the Router configuration. From what I understand it might make sense to branch from those changes and then propagate the max_concurrency through the `RouterConfig` object (see PR). 

Does that sound right?
