### ISSUE TITLE
Environment Variables should be passed from CLI to every module that is running

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#63]
The following option should be added to the Wagi CLI:

`-e NAME=VALUE`

This should be supported for multiple options (`-e foo=bar baz=lurman`). It should also support quoted values: `-e foo="test -e"`.

This should parse the input into name/value string/string pairs, which will be passed to every running module as environment variables.

For example, if two `a.wasm` and `b.wasm` are both running, both should receive all of the name/value pairs sent using `-e`.

**Comment by radu-matei** [comment]
What if `modules.toml` also defined one of the environment variables, which one should take precedence?

**Comment by technosophos** [comment]
@radu-matei raised a good point in a discussion he and I had: How does this related to existing env vars that come in via modules.toml or a bindle.

I think what we want to do is treat the env vars in those locations as _default values_ , and anything that comes in over `-e` overrides those values.

The reasoning behind this has more to do with how we plan on using Wagi: Our current view of Wagi is that a developer will provide the `modules.toml` or the bindle, and the platform/operator will be responsible for running an _instance of_ that application. So each Wagi server is expected to run an _instance_. That is, no one Wagi server (outside of dev) would run multiple "channels" (e.g. dev/stage/prod). Rather, a wagi instance _is_ the channel.

Given that design, the `-e` flag is viewed as a channel-specific override. E.g. Supplying "-e FOO=bar" is essentially the statement that "for this channel (staging), the `$FOO` value should be `bar`, not the developer's default value".
