### ISSUE TITLE
Speed up the output

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#8]
Right now, a module is entirely buffered, and then its contents are length-checked and sent back to the client. This is fine for small files, but would be both slow and resource intensive for larger responses. We can probably figure out a way to stream that content back.

This will break from the CGI spec, but that is okay since the spec was pre-HTTP/2

**Comment by beriberikix** [comment]
Discussing CGI brings me waaay back. But IIRC, better efficiency is why [FastCGI](https://en.wikipedia.org/wiki/FastCGI) was created to as an update to CGI. Have you investigated the use of FastCGI as well?

**Comment by technosophos** [comment]
I did take a look during design, and we probably could do something FastCGI-like. Ultimately, we might be able to get FastCGI times by just figuring out how to cache WebAssembly.

If there are some key features you think might be good to implement sooner rather than later, lemme know.

**Comment by beriberikix** [comment]
Nothing specific comes to mind, but I'll give it some thought!

**Comment by technosophos** [comment]
I was thinking about it a bit, and I think I might be able to replicate a little more of the model from FastCGI's startup strategy. Namely, if I can load the WASM code and perhaps even link it, I should be able to cut the startup time way down. I will give that a try this Friday.

Thanks again for the suggestion.
