### ISSUE TITLE
Encapsulate the router info that is passed to the module.

### ISSUE THREAD

**Issue by technosophos** [deislabs/wagi#80]
Right now, the `Router` has some configuration info that gets passed to the `Module` in the form of long parameter lists on functions. We should probably encapsulate that information in some way.

Example: https://github.com/deislabs/wagi/blob/main/src/runtime/mod.rs#L137

**Comment by technosophos** [comment]
Yeah. Refactoring that into a struct or something would likely result in cleaner code.

**Comment by nitishm** [comment]
Sure simple enough (in theory). I will give it a shot!
